# Task2 name: Simple Calculator
first_number = input("Enter first number: ")
second_number = input("Enter second number: ")
sum = float(first_number) + float(second_number)
print(sum)
difference = float(first_number) - float(second_number)
print(difference)
product = float(first_number) * float(second_number)
print(product)
quotient = float(first_number) / float(second_number)
print(quotient)